# Generated by Django 5.0.6 on 2024-05-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
